sudo: required
services:
    - docker
before_install:
    - docker build -t mr/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true mr/react-test npm run test
after_success:
    - docker build -t ishaqca/multi-client ./client
    - docker build -t ishaqca/multi-server ./server
    - docker build -t ishaqca/multi-nginx ./nginx
    - docker build -t ishaqca/multi-worker ./worker 
# Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to docker hub
    - docker push ishaqca/multi-client
    - docker push ishaqca/multi-server
    - docker push ishaqca/multi-nginx
    - docker push ishaqca/multi-worker  
# deploy to AWS EB
deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-2-330943595153'
    bucket_path: 'docker-multi'
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY